=== RUKSANABR/TASK/XmlEmployee/XmlEmployee/bin/Debug/net8.0/employees.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="Employee">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string" />
							<xs:element name="Department" type="xs:string" />
							<xs:element name="Salary" type="xs:decimal" />
							<xs:element name="JoiningDate" type="xs:date" />
						</xs:sequence>
						<xs:attribute name="id" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="UniqueEmployeeID">
			<xs:selector xpath="Employee"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
</xs:schema>

=== RUKSANABR/TASK/XmlEmployee/XmlEmployee/employees.xml
<?xml version="1.0" encoding="utf-8"?>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employees.xsd">
	<Employee id="E01">
		<Name>Sandra</Name>
		<Department>IT</Department>
		<Salary>60000</Salary>
		<JoiningDate>2021-03-15</JoiningDate>
	</Employee>
	<Employee id="E02">
		<Name>Joel</Name>
		<Department>HR</Department>
		<Salary>55000</Salary>
		<JoiningDate>2019-07-10</JoiningDate>
	</Employee>
	<Employee id="E03">
		<Name>Aparnna</Name>
		<Department>IT</Department>
		<Salary>30000</Salary>
		<JoiningDate>2022-01-05</JoiningDate>
	</Employee>
	<Employee id="E04">
		<Name>vijay</Name>
		<Department>IT</Department>
		<Salary>30000</Salary>
		<JoiningDate>2017-01-05</JoiningDate>
	</Employee>
</Employees>
